routes/admin.php
        Route::get('/users-order/processing', 'Admin\OrderManageController@processingMultiple')->name('user-order-multiple-processing');
        Route::get('/users-order/inprogress', 'Admin\OrderManageController@inProgressMultiple')->name('user-order-multiple-inprogress');
        Route::get('/users-order/completed', 'Admin\OrderManageController@completedMultiple')->name('user-order-multiple-completed');
        Route::get('/users-order/partial', 'Admin\OrderManageController@partialMultiple')->name('user-order-multiple-partial');
        Route::get('/users-order/canceled', 'Admin\OrderManageController@cancelledMultiple')->name('user-order-multiple-canceled');
        Route::get('/users-order/refunded', 'Admin\OrderManageController@refundedMultiple')->name('user-order-multiple-refunded');


        Route::get('/service', 'ServiceController@create')->name('service.add');
        Route::get('/services', 'ServiceController@index')->name('service.show');
        Route::post('/services', 'ServiceController@store')->name('service.store');
        Route::get('/search-service', 'ServiceController@search')->name('service-search');
        Route::post('/search-service/status/{id?}', 'ServiceController@statusChange')->name('service.status.change');

        Route::get('/service-active', 'ServiceController@serviceActive')->name('service-active');
        Route::get('/service-deActive', 'ServiceController@serviceDeActive')->name('service-deactive');
        Route::get('/service/{id}', 'ServiceController@edit')->name('service.edit');
        Route::post('/service/update', 'ServiceController@update')->name('service.update');
        Route::get('/get-service', 'ServiceController@getService')->name('get.service');
        Route::get('/service-multiple-active', 'ServiceController@activeMultiple')->name('service-multiple-active');
        Route::get('/service-multiple-deActive', 'ServiceController@deactiveMultiple')->name('service-multiple-deactive');
        Route::get('/service-multiple-delete', 'ServiceController@deleteMultiple')->name('service-multiple-delete');


        Route::get('/category/add', 'CategoryController@create')->name('category.add');
        Route::post('/category', 'CategoryController@store')->name('category.store');

        Route::get('/category-active', 'CategoryController@categoryActive')->name('category-active');
        Route::get('/category-deactive', 'CategoryController@categoryDeactive')->name('category-deactive');
        Route::get('/category/{id}', 'CategoryController@edit')->name('category.edit');
        Route::post('/category/update', 'CategoryController@update')->name('category.update');
        Route::get('/categories', 'CategoryController@index')->name('category.show');
        Route::post('/category/status/{id?}', 'CategoryController@statusChange')->name('category.status.change');
        Route::get('/get-category', 'CategoryController@show')->name('get.category');
        // search
        Route::get('/search-category', 'CategoryController@search')->name('category-search');
        Route::get('/category-multiple-active', 'CategoryController@activeMultiple')->name('category-multiple-active');
        Route::get('/category-multiple-deactive', 'CategoryController@deactiveMultiple')->name('category-multiple-deactive');


        Route::resource('api-provider', 'ApiProviderController', ['as' => 'provider']);
        // search
        Route::get('/search-provider', 'ApiProviderController@search')->name('provider-search');

        Route::post('api-provider/status{id}', 'ApiProviderController@changeStatus')->name('provider.status');
        Route::post('api-provider/priceUpdate/{id}', 'ApiProviderController@priceUpdate')->name('provider.priceUpdate');
        Route::post('api-provider/balanceUpdate/{id}', 'ApiProviderController@balanceUpdate')->name('provider.balanceUpdate');

        Route::post('/api-services', 'ApiProviderController@getApiServices')->name('api.services');
        Route::post('/api-services/import', 'ApiProviderController@import')->name('api.service.import');
        Route::post('/api-services/import/multi', 'ApiProviderController@importMulti')->name('api.service.import.multi');
        // jquery autocomplete search
        Route::get('/get-provider', 'ApiProviderController@providerShow')->name('get.provider');
        //api provider multiple
        Route::get('/apiprovider-multiple-active', 'ApiProviderController@activeMultiple')->name('apiprovider-multiple-active');
        Route::get('/apiprovider-multiple-deactive', 'ApiProviderController@deActiveMultiple')->name('apiprovider-multiple-deactive');


        /* ===== ADMIN Mange Theme ===== */
        Route::get('/manage/theme', 'ControlController@manageTheme')->name('manage.theme');
        Route::put('/activate/theme/{name}', 'ControlController@activateTheme')->name('activate.themeUpdate');

        /* ======== Plugin =======*/
        Route::get('/plugin-config', 'ControlController@pluginConfig')->name('plugin.config');
        Route::match(['get', 'post'], 'tawk-config', 'ControlController@tawkConfig')->name('tawk.control');
        Route::match(['get', 'post'], 'fb-messenger-config', 'ControlController@fbMessengerConfig')->name('fb.messenger.control');
        Route::match(['get', 'post'], 'google-recaptcha', 'ControlController@googleRecaptchaConfig')->name('google.recaptcha.control');
        Route::match(['get', 'post'], 'google-analytics', 'ControlController@googleAnalyticsConfig')->name('google.analytics.control');
        Route::match(['get', 'post'], 'currency-exchange-api-config', 'ControlController@currencyExchangeApiConfig')->name('currency.exchange.api.config');

        Route::get('/logo-seo', 'ControlController@logoSeo')->name('logo-seo');
        Route::put('/logoUpdate', 'ControlController@logoUpdate')->name('logoUpdate');
        Route::put('/seoUpdate', 'ControlController@seoUpdate')->name('seoUpdate');

        Route::get('/breadcrumb', 'ControlController@breadcrumb')->name('breadcrumb');
        Route::put('/breadcrumb', 'ControlController@breadcrumbUpdate')->name('breadcrumbUpdate');


        Route::any('/basic-controls', 'ControlController@index')->name('basic-controls');
        Route::post('/basic-controls', 'ControlController@updateConfigure')->name('basic-controls.update');

        Route::get('/color-settings', 'ControlController@colorSettings')->name('color-settings');
        Route::post('/color-settings', 'ControlController@colorSettingsUpdate')->name('color-settings.update');

        Route::get('/email-controls', 'EmailTemplateController@emailControl')->name('email-controls');
        Route::post('/email-controls', 'EmailTemplateController@emailConfigure')->name('email-controls.update');
        Route::post('/email-controls/action', 'EmailTemplateController@emailControlAction')->name('email-controls.action');
        Route::post('/email/test', 'EmailTemplateController@testEmail')->name('testEmail');

        Route::get('/email-template', 'EmailTemplateController@show')->name('email-template.show');
        Route::get('/email-template/edit/{id}', 'EmailTemplateController@edit')->name('email-template.edit');
        Route::post('/email-template/update/{id}', 'EmailTemplateController@update')->name('email-template.update');

        //sms control
        Route::match(['get', 'post'], '/sms-controls', 'SmsControlController@smsConfig')->name('sms.config');
        Route::post('/sms-controls/action', 'SmsControlController@smsControlAction')->name('sms-controls.action');

        Route::get('/sms/control-delete/{id}', 'SmsControlController@destroy')->name('smsControl_delete');
        Route::get('/sms-template', 'SmsTemplateController@show')->name('sms-template');
        Route::get('/sms-template/edit/{id}', 'SmsTemplateController@edit')->name('sms-template.edit');
        Route::post('/sms-template/update/{id}', 'SmsTemplateController@update')->name('sms-template.update');


        Route::get('/notify-config', 'Admin\NotifyController@notifyConfig')->name('notify-config');
        Route::post('/notify-config', 'Admin\NotifyController@notifyConfigUpdate')->name('notify-config.update');

        Route::get('/notify-template', 'Admin\NotifyController@show')->name('notify-template.show');
        Route::get('/notify-template/edit/{id}', 'Admin\NotifyController@edit')->name('notify-template.edit');
        Route::post('/notify-template/update/{id}', 'Admin\NotifyController@update')->name('notify-template.update');


        Route::get('/order', 'OrderController@index')->name('order');
        Route::post('/order/status', 'OrderController@statusChange')->name('order.status.change');
        Route::get('/order/edit/{id}', 'OrderController@edit')->name('order.edit');
        Route::post('/order/update/{id}', 'OrderController@update')->name('order.update');
        Route::delete('/order/destroy/{id}', 'OrderController@destroy')->name('order.destroy');
        Route::get('/get-service', 'OrderController@getservice')->name('get.service');
        Route::get('/get-user', 'OrderController@getuser')->name('get.user');
        Route::get('/search-order', 'OrderController@search')->name('order-search');

        Route::get('/order/awaiting', 'OrderController@awaiting')->name('awaiting');
        Route::get('/order/pending', 'OrderController@pending')->name('pending');
        Route::get('/order/processing', 'OrderController@processing')->name('processing');
        Route::get('/order/progress', 'OrderController@progress')->name('progress');
        Route::get('/order/completed', 'OrderController@completed')->name('completed');
        Route::get('/order/partial', 'OrderController@partial')->name('partial');
        Route::get('/order/canceled', 'OrderController@canceled')->name('canceled');
        Route::get('/order/refunded', 'OrderController@refunded')->name('refunded');
        // transaction
        Route::get('/transaction', 'OrderController@transaction')->name('user-transaction');

routes/web.php
<?php

use App\Http\Controllers\Admin\LogController;
use App\Models\Service;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
require __DIR__ . '/admin.php';
Route::get('/clear', function () {
    $output = new \Symfony\Component\Console\Output\BufferedOutput();
    Artisan::call('optimize:clear', array(), $output);
    return $output->fetch();
})->name('/clear');


Route::get('queue-work', function () {
    return Illuminate\Support\Facades\Artisan::call('queue:work', ['--stop-when-empty' => true]);
})->name('queue.work');
Route::get('schedule-run', function () {
    return Illuminate\Support\Facades\Artisan::call('schedule:run');
});
Route::get('migrate', function () {
    return Illuminate\Support\Facades\Artisan::call('migrate');
});

Route::get('/themeMode/{themeType?}', function ($themeType = 'true') {
    session()->put('dark-mode', $themeType);
    return $themeType;
})->name('themeMode');

Route::get('cron', 'FrontendController@cron')->name('cron');





Route::middleware('Maintenance')->group(function () {
    Route::get('/user', 'Auth\LoginController@showLoginForm')->name('login-form');

    Auth::routes(['verify' => true]);

    Route::group(['middleware' => ['guest']], function () {
        Route::get('register/{sponsor?}', 'Auth\RegisterController@sponsor')->name('register.sponsor');
    });


    Route::group(['middleware' => ['auth'], 'prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('/check', 'VerificationController@check')->name('check');
        Route::get('/resend_code', 'VerificationController@resendCode')->name('resendCode');
        Route::post('/mail-verify', 'VerificationController@mailVerify')->name('mailVerify');
        Route::post('/sms-verify', 'VerificationController@smsVerify')->name('smsVerify');
        Route::post('/twoFA-Verify', 'VerificationController@twoFAverify')->name('twoFA-Verify');

        Route::middleware('userCheck')->group(function () {

            Route::get('/dashboard', 'HomeController@index')->name('home');

            Route::get('add-fund', 'HomeController@addFund')->name('addFund');
            Route::post('add-fund', 'PaymentController@addFundRequest')->name('addFund.request');
            Route::get('addFundConfirm', 'PaymentController@depositConfirm')->name('addFund.confirm');
            Route::post('addFundConfirm', 'PaymentController@fromSubmit')->name('addFund.fromSubmit');


            //transaction
            Route::get('/transaction', 'HomeController@transaction')->name('transaction');
            Route::get('/transaction-search', 'HomeController@transactionSearch')->name('transaction.search');
            Route::get('fund-history', 'HomeController@fundHistory')->name('fund-history');
            Route::get('fund-history-search', 'HomeController@fundHistorySearch')->name('fund-history.search');

            Route::get('/profile', 'HomeController@profile')->name('profile');
            Route::post('/updateProfile', 'HomeController@updateProfile')->name('updateProfile');
            Route::put('/updateInformation', 'HomeController@updateInformation')->name('updateInformation');
            Route::post('/updatePassword', 'HomeController@updatePassword')->name('updatePassword');

            Route::get('/apiKey', 'HomeController@apiKey')->name('apiKey');


            Route::get('/referral', 'HomeController@referral')->name('referral');
            Route::get('/referral-bonus', 'HomeController@referralBonus')->name('referral.bonus');
            Route::get('/referral-bonus-search', 'HomeController@referralBonusSearch')->name('referral.bonus.search');


            //order
            Route::resource('order', 'User\OrderController');
            // Route::post('order', 'User\OrderController@store')->name('user.order.store');;

            Route::get('/orders', 'User\OrderController@search')->name('order.search');
            Route::post('/order/status', 'User\OrderController@statusChange')->name('order.status.change');
            Route::get('/orders/{status}', 'User\OrderController@statusSearch')->name('order.status.search');
            Route::get('/mass/orders', 'User\OrderController@massOrder')->name('order.mass');
            Route::post('/mass/orders', 'User\OrderController@masOrderStore')->name('order.mass.store');
            Route::get('/get-service', 'ServiceController@getservice')->name('get.service');

            //order search
            Route::get('/services', 'User\ServiceController@index')->name('service.show');
            Route::get('/services/{id}', 'User\ServiceController@services')->name('category.services');
            Route::get('/service-search', 'User\ServiceController@search')->name('service.search');
            Route::get('/neworder/{id}', 'User\ServiceController@order')->name('category.order');


            Route::get('/api/docs', 'User\ApiController@index')->name('api.docs');
            Route::post('/keyGenerate', 'User\ApiController@apiGenerate')->name('keyGenerate');

            // TWO-FACTOR SECURITY
            Route::get('/twostep-security', 'HomeController@twoStepSecurity')->name('twostep.security');
            Route::post('twoStep-enable', 'HomeController@twoStepEnable')->name('twoStepEnable');
            Route::post('twoStep-disable', 'HomeController@twoStepDisable')->name('twoStepDisable');

            // Support Ticket
            Route::group(['prefix' => 'ticket', 'as' => 'ticket.'], function () {
                Route::get('/', 'User\SupportController@index')->name('list');
                Route::get('/create', 'User\SupportController@create')->name('create');
                Route::post('/create', 'User\SupportController@store')->name('store');
                Route::get('/view/{ticket}', 'User\SupportController@view')->name('view');
                Route::put('/reply/{ticket}', 'User\SupportController@reply')->name('reply');
                Route::get('/download/{ticket}', 'User\SupportController@download')->name('download');
            });

            Route::post('/service', function (Request $request) {
                $parent_id = $request->cat_id;
                $services = Service::where('category_id', $parent_id)->where('service_status', 1)->get();
                return response()->json($services);
            })->name('service');


            Route::get('push-notification-show', 'SiteNotificationController@show')->name('push.notification.show');
            Route::get('push.notification.readAll', 'SiteNotificationController@readAll')->name('push.notification.readAll');
            Route::get('push-notification-readAt/{id}', 'SiteNotificationController@readAt')->name('push.notification.readAt');

            Route::get('/user-service', 'User\OrderController@userservice')->name('service_id');

        });
    });

    Route::match(['get', 'post'], 'success', 'PaymentController@success')->name('success');
    Route::match(['get', 'post'], 'failed', 'PaymentController@failed')->name('failed');
    Route::match(['get', 'post'], 'payment/{code}/{trx?}/{type?}', 'PaymentController@gatewayIpn')->name('ipn');


    Route::get('/language/{code?}', 'FrontendController@language')->name('language');


    Route::get('/blog-details/{slug}/{id}', 'FrontendController@blogDetails')->name('blogDetails');
    Route::get('/blog', 'FrontendController@blog')->name('blog');

    Route::get('/', 'FrontendController@index')->name('home');
    Route::get('/about', 'FrontendController@about')->name('about');
    Route::get('/services', 'FrontendController@services')->name('services');
    Route::get('/service-search', 'FrontendController@serviceSearch')->name('service.search');


    Route::post('/subscribe', 'FrontendController@subscribe')->name('subscribe');


    Route::get('/faq', 'FrontendController@faq')->name('faq');
    Route::get('/api-docs', 'FrontendController@apiDocs')->name('apiDocs');
    Route::get('/contact', 'FrontendController@contact')->name('contact');
    Route::post('/contact', 'FrontendController@contactSend')->name('contact.send');
    Route::get('/{getLink}/{content_id}', 'FrontendController@getLink')->name('getLink');

});

resources/views/admin/pages/api_providers/add.blade.php
@extends('admin.layouts.app')
@section('title')
    @lang('API Controls')
@endsection
@section('content')
    <div class="center">
        <select id="api">
            <option selected> @lang('Select Provider')</option>
            @foreach($providerData as $key => $provider)
                <option data-slug="{{$key}}" data-url="{{$provider['url']}}" data-name="{{$provider['api_name']}}">
                    {{$provider['api_name']}}</option>
            @endforeach
        </select>
    </div>
    <div class="card card-primary m-0 m-md-4 my-4 m-md-0 shadow">
        <div class="card-body">
            <form method="post" action=" {{route('admin.provider.api-provider.store')}} " enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group ">
                            <label>@lang('Api Name')</label>
                            <input type="text" id="api_name" name="api_name" value="{{ old('api_name') }}" required
                                   class="form-control form-control-sm">
                            <div class="invalid-feedback">@lang('Please fill in the api name')</div>
                            @error('api_name')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group ">
                            <label>@lang('API Key')</label>
                            <input type="text" name="api_key" value="{{ old('api_key') }}" required="required"
                                   class="form-control form-control-sm">
                            <div class="invalid-feedback">@lang('Please fill in the api key')</div>
                            @error('api_key')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group ">
                            <label>@lang('URL')</label>
                            <input type="text" id="url" name="url" value="{{ old('url') }}" required="required"
                                   class="form-control form-control-sm">
                            <div class="invalid-feedback">@lang('Please fill in the url')</div>

                            @error('url')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group ">
                            <label>@lang('Slug')</label>
                            <input type="text" id="slug" name="slug" value="{{ old('slug') }}"
                                   class="form-control form-control-sm">
                            <div class="invalid-feedback">@lang('Please fill in the slug')</div>

                            @error('url')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group ">
                            <label class="d-block">@lang('Status')</label>
                            <div class="custom-switch-btn w-md-50">
                                <input type='hidden' value='1' name='status'>
                                <input type="checkbox" name="status" class="custom-switch-checkbox" id="status"
                                       value="0">
                                <label class="custom-switch-checkbox-label" for="status">
                                    <span class="custom-switch-checkbox-inner"></span>
                                    <span class="custom-switch-checkbox-switch"></span>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="category_description">@lang('Description')</label>
                    <textarea class="form-control" id="description" rows="3"
                              name="description">{{ old('description') }}</textarea>
                    <div class="invalid-feedback">@lang('Please fill in the description')</div>

                    @error('description')
                    <span class="text-danger">{{ $message }}</span>
                    @enderror
                </div>
                <div class="submit-btn-wrapper mt-md-5 text-center text-md-left">
                    <button type="submit" class=" btn  btn-primary btn-block mt-3">
                        <span>@lang('Add API Provider')</span></button>
                </div>
            </form>
        </div>
    </div>

@endsection
@push('js')
    <script>
        "use strict";
        $(document).ready(function (e) {
            $('#api').change(function () {
                var option = this.selectedOptions[0];
                const url = $(option).data('url');
                const name = $(option).data('name');
                const slug = $(option).data('slug');
                $('#slug').val(slug);
                $('#api_name').val(name);
                $('#url').val(url);
                console.log(url);
            })
        });
    </script>
@endpush

resources/views/admin/pages/api_providers/edit.blade.php
@extends('admin.layouts.app')
@section('title')
    @lang('Edit Api')
@endsection
@section('content')
    <div class="card card-primary m-0 m-md-4 my-4 m-md-0">
        <div class="card-body">
            <form method="POST" action=" {{route('admin.provider.api-provider.update',[$provider->id]) }} " enctype="multipart/form-data">
                @method('put')
                @csrf
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group ">
                            <label>@lang('Api Name')</label>
                            <input type="text" name="api_name" value="{{ old('api_name',$provider->api_name) }}" required="required" class="form-control form-control-sm">
                            <div class="invalid-feedback">@lang('Please fill in the api name')</div>

                            @error('api_name')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group ">
                            <label>@lang('API Key')</label>
                            <input type="text" name="api_key"  value="{{ old('api_key',$provider->api_key) }}"  required="required" class="form-control form-control-sm">
                            <div class="invalid-feedback">@lang('Please fill in the api key')</div>
                            @error('api_key')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group ">
                            <label>@lang('URL')</label>
                            <input type="text" name="url" value="{{ old('url',$provider->url) }}" required="required" class="form-control form-control-sm">
                            <div class="invalid-feedback">@lang('Please fill in the url')</div>
                            @error('url')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group ">
                            <label>@lang('Slug')</label>
                            <input type="text" name="slug" value="{{ old('slug',$provider->slug) }}"
                                   class="form-control form-control-sm">
                            <div class="invalid-feedback">@lang('Please fill in the slug')</div>

                            @error('url')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group ">
                            <label class="d-block">@lang('Status')</label>
                            <div class="custom-switch-btn w-md-50">
                                <input type='hidden' value='1' name='status'>
                                <input type="checkbox" name="status" class="custom-switch-checkbox" id="status" value = "0" <?php if( $provider->status == 0):echo 'checked'; endif ?> >
                                <label class="custom-switch-checkbox-label" for="status">
                                    <span class="custom-switch-checkbox-inner"></span>
                                    <span class="custom-switch-checkbox-switch"></span>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="category_description">@lang('Description')</label>
                    <textarea class="form-control" id="description" rows="3" name="description" >{{ old('description',$provider->description) }}</textarea>
                    <div class="invalid-feedback">@lang('Please fill in the description')</div>

                    @error('description')
                    <span class="text-danger">{{ $message }}</span>
                    @enderror
                </div>
                <div class="submit-btn-wrapper mt-md-5 text-center text-md-left">
                    <button type="submit" class="btn waves-effect waves-light btn-rounded btn-primary btn-block mt-3"><span>@lang('Update API Provider')</span> </button>
                </div>
            </form>

        </div>
    </div>
@endsection