routes/admin.php
<?php

use App\Http\Controllers\Admin\LogController;
use App\Models\Service;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', 'Admin\LoginController@showLoginForm')->name('login-page');
    Route::post('/', 'Admin\LoginController@login')->name('login');
    Route::post('/logout', 'Admin\LoginController@logout')->name('logout');


    Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('/password/reset', 'Admin\Auth\ResetPasswordController@reset')->name('password.update');


    Route::group(['middleware' => ['auth:admin']], function () {
        Route::get('/dashboard', 'Admin\DashboardController@dashboard')->name('dashboard');

        Route::get('push-notification-show', 'SiteNotificationController@showByAdmin')->name('push.notification.show');
        Route::get('push.notification.readAll', 'SiteNotificationController@readAllByAdmin')->name('push.notification.readAll');
        Route::get('push-notification-readAt/{id}', 'SiteNotificationController@readAt')->name('push.notification.readAt');
        Route::match(['get', 'post'], 'pusher-config', 'SiteNotificationController@pusherConfig')->name('pusher.config');


        Route::get('/referral-commission', 'Admin\DashboardController@referralCommission')->name('referral-commission');
        Route::post('/referral-commission', 'Admin\DashboardController@referralCommissionStore')->name('referral-commission.store');
        Route::post('/referral-commission/action', 'Admin\DashboardController@referralCommissionAction')->name('referral-commission.action');


        Route::get('/profile', 'Admin\DashboardController@profile')->name('profile');
        Route::put('/profile', 'Admin\DashboardController@profileUpdate')->name('profileUpdate');
        Route::get('/password', 'Admin\DashboardController@password')->name('password');
        Route::put('/password', 'Admin\DashboardController@passwordUpdate')->name('passwordUpdate');


        Route::get('payment-methods', 'Admin\PaymentMethodController@index')->name('payment.methods');
        Route::post('payment-methods/deactivate', 'Admin\PaymentMethodController@deactivate')->name('payment.methods.deactivate');
        Route::get('payment-methods/deactivate', 'Admin\PaymentMethodController@deactivate')->name('payment.methods.deactivate-page');
        Route::post('sort-payment-methods', 'Admin\PaymentMethodController@sortPaymentMethods')->name('sort.payment.methods');
        Route::get('payment-methods/edit/{id}', 'Admin\PaymentMethodController@edit')->name('edit.payment.methods');
        Route::put('payment-methods/update/{id}', 'Admin\PaymentMethodController@update')->name('update.payment.methods');


        // Manual Methods
        Route::get('payment-methods/manual', 'Admin\ManualGatewayController@index')->name('deposit.manual.index');
        Route::get('payment-methods/manual/new', 'Admin\ManualGatewayController@create')->name('deposit.manual.create');
        Route::post('payment-methods/manual/new', 'Admin\ManualGatewayController@store')->name('deposit.manual.store');
        Route::get('payment-methods/manual/edit/{id}', 'Admin\ManualGatewayController@edit')->name('deposit.manual.edit');
        Route::put('payment-methods/manual/update/{id}', 'Admin\ManualGatewayController@update')->name('deposit.manual.update');


        Route::get('payment/pending', 'Admin\PaymentLogController@pending')->name('payment.pending');
        Route::put('payment/action/{id}', 'Admin\PaymentLogController@action')->name('payment.action');
        Route::get('payment/log', 'Admin\PaymentLogController@index')->name('payment.log');
        Route::get('payment/search', 'Admin\PaymentLogController@search')->name('payment.search');


        Route::get('/users', 'Admin\UsersController@index')->name('users');
        Route::get('/users/search', 'Admin\UsersController@search')->name('users.search');
        Route::post('/users-active', 'Admin\UsersController@activeMultiple')->name('user-multiple-active');
        Route::post('/users-inactive', 'Admin\UsersController@inactiveMultiple')->name('user-multiple-inactive');
        Route::get('/email-send', 'Admin\UsersController@sendMailUsers')->name('users.email-send');
        Route::post('/email-send', 'Admin\UsersController@sendMailUsersStore')->name('users.email-send.store');
        Route::get('/user/edit/{id}', 'Admin\UsersController@userEdit')->name('user-edit');
        Route::post('/user/update/{id}', 'Admin\UsersController@userUpdate')->name('user-update');
        Route::post('/user/password/{id}', 'Admin\UsersController@passwordUpdate')->name('userPasswordUpdate');
        Route::post('/user/balance-update/{id}', 'Admin\UsersController@userBalanceUpdate')->name('user-balance-update');
        Route::get('/user/send-email/{id}', 'Admin\UsersController@sendEmail')->name('send-email');
        Route::post('/user/send-email/{id}', 'Admin\UsersController@sendMailUser')->name('user.email-send');
        Route::post('/user/loginAccount/{id}', 'Admin\UsersController@loginAccount')->name('user-loginAccount');


        Route::get('/user/custom-rate/{id}', 'Admin\UsersController@customRate')->name('user.customRate');
        Route::get('/user/getService', 'Admin\UsersController@getService')->name('user.getService');
        Route::post('/user/setServiceRate', 'Admin\UsersController@setServiceRate')->name('user.setServiceRate');

        Route::get('/user/updateServiceRate', 'Admin\UsersController@updateServiceRate')->name('user.updateServiceRate');
        Route::get('/user/deleteServiceRate', 'Admin\UsersController@deleteServiceRate')->name('user.deleteServiceRate');

        Route::post('/user/keyGenerate/{id}', 'Admin\UsersController@keyGenerate')->name('user.keyGenerate');

        Route::get('/user/transaction/{id}', 'Admin\UsersController@transaction')->name('user.transaction');
        Route::get('/user/fundLog/{id}', 'Admin\UsersController@funds')->name('user.fundLog');


        Route::get('/get-user-name', 'Admin\OrderManageController@getUsername')->name('get.user-name');
        Route::get('/user/order/{id}', 'Admin\OrderManageController@userOrder')->name('user-order');
        Route::get('/user/order-search', 'Admin\OrderManageController@userOrderSearch')->name('user-order-search');
        Route::get('/user-order-service/{id}', 'Admin\OrderManageController@userServiceEdit')->name('user-service-edit');
        //user order


        Route::get('/usersOrderChangeStatus', 'Admin\OrderManageController@usersOrderChangeStatus')->name('usersOrderChangeStatus');

        Route::get('/users-order/awaiting', 'Admin\OrderManageController@awaitingMultiple')->name('user-order-multiple-awaiting');
        Route::get('/users-order/awaiting', 'Admin\OrderManageController@awaitingMultiple')->name('user-order-multiple-awaiting');
        Route::get('/users-order/pending', 'Admin\OrderManageController@pendingMultiple')->name('user-order-multiple-pending');
        Route::get('/users-order/processing', 'Admin\OrderManageController@processingMultiple')->name('user-order-multiple-processing');
        Route::get('/users-order/inprogress', 'Admin\OrderManageController@inProgressMultiple')->name('user-order-multiple-inprogress');
        Route::get('/users-order/completed', 'Admin\OrderManageController@completedMultiple')->name('user-order-multiple-completed');
        Route::get('/users-order/partial', 'Admin\OrderManageController@partialMultiple')->name('user-order-multiple-partial');
        Route::get('/users-order/canceled', 'Admin\OrderManageController@cancelledMultiple')->name('user-order-multiple-canceled');
        Route::get('/users-order/refunded', 'Admin\OrderManageController@refundedMultiple')->name('user-order-multiple-refunded');


        Route::get('/service', 'ServiceController@create')->name('service.add');
        Route::get('/services', 'ServiceController@index')->name('service.show');
        Route::post('/services', 'ServiceController@store')->name('service.store');
        Route::get('/search-service', 'ServiceController@search')->name('service-search');
        Route::post('/search-service/status/{id?}', 'ServiceController@statusChange')->name('service.status.change');

        Route::get('/service-active', 'ServiceController@serviceActive')->name('service-active');
        Route::get('/service-deActive', 'ServiceController@serviceDeActive')->name('service-deactive');
        Route::get('/service/{id}', 'ServiceController@edit')->name('service.edit');
        Route::post('/service/update', 'ServiceController@update')->name('service.update');
        Route::get('/get-service', 'ServiceController@getService')->name('get.service');
        Route::get('/service-multiple-active', 'ServiceController@activeMultiple')->name('service-multiple-active');
        Route::get('/service-multiple-deActive', 'ServiceController@deactiveMultiple')->name('service-multiple-deactive');
        Route::get('/service-multiple-delete', 'ServiceController@deleteMultiple')->name('service-multiple-delete');


        Route::get('/category/add', 'CategoryController@create')->name('category.add');
        Route::post('/category', 'CategoryController@store')->name('category.store');

        Route::get('/category-active', 'CategoryController@categoryActive')->name('category-active');
        Route::get('/category-deactive', 'CategoryController@categoryDeactive')->name('category-deactive');
        Route::get('/category/{id}', 'CategoryController@edit')->name('category.edit');
        Route::post('/category/update', 'CategoryController@update')->name('category.update');

routes/web.php
<?php

use App\Http\Controllers\Admin\LogController;
use App\Models\Service;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
require __DIR__ . '/admin.php';
Route::get('/clear', function () {
    $output = new \Symfony\Component\Console\Output\BufferedOutput();
    Artisan::call('optimize:clear', array(), $output);
    return $output->fetch();
})->name('/clear');


Route::get('queue-work', function () {
    return Illuminate\Support\Facades\Artisan::call('queue:work', ['--stop-when-empty' => true]);
})->name('queue.work');
Route::get('schedule-run', function () {
    return Illuminate\Support\Facades\Artisan::call('schedule:run');
});
Route::get('migrate', function () {
    return Illuminate\Support\Facades\Artisan::call('migrate');
});

Route::get('/themeMode/{themeType?}', function ($themeType = 'true') {
    session()->put('dark-mode', $themeType);
    return $themeType;
})->name('themeMode');

Route::get('cron', 'FrontendController@cron')->name('cron');





Route::middleware('Maintenance')->group(function () {
    Route::get('/user', 'Auth\LoginController@showLoginForm')->name('login-form');

    Auth::routes(['verify' => true]);

    Route::group(['middleware' => ['guest']], function () {
        Route::get('register/{sponsor?}', 'Auth\RegisterController@sponsor')->name('register.sponsor');
    });


    Route::group(['middleware' => ['auth'], 'prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('/check', 'VerificationController@check')->name('check');
        Route::get('/resend_code', 'VerificationController@resendCode')->name('resendCode');
        Route::post('/mail-verify', 'VerificationController@mailVerify')->name('mailVerify');
        Route::post('/sms-verify', 'VerificationController@smsVerify')->name('smsVerify');
        Route::post('/twoFA-Verify', 'VerificationController@twoFAverify')->name('twoFA-Verify');

        Route::middleware('userCheck')->group(function () {

            Route::get('/dashboard', 'HomeController@index')->name('home');

            Route::get('add-fund', 'HomeController@addFund')->name('addFund');
            Route::post('add-fund', 'PaymentController@addFundRequest')->name('addFund.request');
            Route::get('addFundConfirm', 'PaymentController@depositConfirm')->name('addFund.confirm');
            Route::post('addFundConfirm', 'PaymentController@fromSubmit')->name('addFund.fromSubmit');


            //transaction
            Route::get('/transaction', 'HomeController@transaction')->name('transaction');
            Route::get('/transaction-search', 'HomeController@transactionSearch')->name('transaction.search');
            Route::get('fund-history', 'HomeController@fundHistory')->name('fund-history');
            Route::get('fund-history-search', 'HomeController@fundHistorySearch')->name('fund-history.search');

            Route::get('/profile', 'HomeController@profile')->name('profile');
            Route::post('/updateProfile', 'HomeController@updateProfile')->name('updateProfile');
            Route::put('/updateInformation', 'HomeController@updateInformation')->name('updateInformation');
            Route::post('/updatePassword', 'HomeController@updatePassword')->name('updatePassword');

            Route::get('/apiKey', 'HomeController@apiKey')->name('apiKey');


            Route::get('/referral', 'HomeController@referral')->name('referral');
            Route::get('/referral-bonus', 'HomeController@referralBonus')->name('referral.bonus');
            Route::get('/referral-bonus-search', 'HomeController@referralBonusSearch')->name('referral.bonus.search');


            //order
            Route::resource('order', 'User\OrderController');
            // Route::post('order', 'User\OrderController@store')->name('user.order.store');;

            Route::get('/orders', 'User\OrderController@search')->name('order.search');
            Route::post('/order/status', 'User\OrderController@statusChange')->name('order.status.change');
            Route::get('/orders/{status}', 'User\OrderController@statusSearch')->name('order.status.search');
            Route::get('/mass/orders', 'User\OrderController@massOrder')->name('order.mass');
            Route::post('/mass/orders', 'User\OrderController@masOrderStore')->name('order.mass.store');
            Route::get('/get-service', 'ServiceController@getservice')->name('get.service');

            //order search
            Route::get('/services', 'User\ServiceController@index')->name('service.show');
            Route::get('/services/{id}', 'User\ServiceController@services')->name('category.services');
            Route::get('/service-search', 'User\ServiceController@search')->name('service.search');
            Route::get('/neworder/{id}', 'User\ServiceController@order')->name('category.order');


            Route::get('/api/docs', 'User\ApiController@index')->name('api.docs');
            Route::post('/keyGenerate', 'User\ApiController@apiGenerate')->name('keyGenerate');

            // TWO-FACTOR SECURITY
            Route::get('/twostep-security', 'HomeController@twoStepSecurity')->name('twostep.security');
            Route::post('twoStep-enable', 'HomeController@twoStepEnable')->name('twoStepEnable');
            Route::post('twoStep-disable', 'HomeController@twoStepDisable')->name('twoStepDisable');

            // Support Ticket
            Route::group(['prefix' => 'ticket', 'as' => 'ticket.'], function () {
                Route::get('/', 'User\SupportController@index')->name('list');
                Route::get('/create', 'User\SupportController@create')->name('create');
                Route::post('/create', 'User\SupportController@store')->name('store');
                Route::get('/view/{ticket}', 'User\SupportController@view')->name('view');
                Route::put('/reply/{ticket}', 'User\SupportController@reply')->name('reply');
                Route::get('/download/{ticket}', 'User\SupportController@download')->name('download');
            });

            Route::post('/service', function (Request $request) {
                $parent_id = $request->cat_id;
                $services = Service::where('category_id', $parent_id)->where('service_status', 1)->get();
                return response()->json($services);
            })->name('service');


            Route::get('push-notification-show', 'SiteNotificationController@show')->name('push.notification.show');
            Route::get('push.notification.readAll', 'SiteNotificationController@readAll')->name('push.notification.readAll');
            Route::get('push-notification-readAt/{id}', 'SiteNotificationController@readAt')->name('push.notification.readAt');

            Route::get('/user-service', 'User\OrderController@userservice')->name('service_id');

        });
    });

    Route::match(['get', 'post'], 'success', 'PaymentController@success')->name('success');
    Route::match(['get', 'post'], 'failed', 'PaymentController@failed')->name('failed');
    Route::match(['get', 'post'], 'payment/{code}/{trx?}/{type?}', 'PaymentController@gatewayIpn')->name('ipn');


    Route::get('/language/{code?}', 'FrontendController@language')->name('language');


    Route::get('/blog-details/{slug}/{id}', 'FrontendController@blogDetails')->name('blogDetails');
    Route::get('/blog', 'FrontendController@blog')->name('blog');

    Route::get('/', 'FrontendController@index')->name('home');
    Route::get('/about', 'FrontendController@about')->name('about');
    Route::get('/services', 'FrontendController@services')->name('services');
    Route::get('/service-search', 'FrontendController@serviceSearch')->name('service.search');


    Route::post('/subscribe', 'FrontendController@subscribe')->name('subscribe');


    Route::get('/faq', 'FrontendController@faq')->name('faq');
    Route::get('/api-docs', 'FrontendController@apiDocs')->name('apiDocs');
    Route::get('/contact', 'FrontendController@contact')->name('contact');
    Route::post('/contact', 'FrontendController@contactSend')->name('contact.send');
    Route::get('/{getLink}/{content_id}', 'FrontendController@getLink')->name('getLink');

});

resources/views/themes/darkmode/services/search-service.blade.php
@extends($theme.'layouts.app')
@section('title', trans('Search Service'))

@section('content')

    <section class="service-page">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="search-area">
                        <form action="{{ route('service.search') }}" method="get">
                            <div class="row g-3">
                                <div class="col-md-4 input-box">
                                    <input type="text" name="service" value="{{@request()->service}}" class="form-control" placeholder="@lang('Search for Services')" />
                                </div>
                                <div class="input-box col-md-4">
                                    <select name="category" id="category" class="form-select statusfield">
                                        <option value="">@lang('All Category')</option>
                                        @foreach($categories as $category)
                                            <option value="{{$category->id}}" {{($category->id == @request()->category) ? 'selected' : ''}}>
                                                @lang($category->category_title)
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="col-md-4">
                                    <button type="submit" class="btn-Msader w-100"><i class="fas fa-search"></i> @lang('Search')</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <div class="accordion" id="accordionExample">
                        @forelse($services as $key => $service)
                            <div class="accordion-item">
                                <h5 class="accordion-header" id="heading{{slug($key)}}">
                                    <button class="accordion-button {{ $key == 0 ? '' : 'collapsed' }}" type="button" data-bs-toggle="collapse"
                                        data-bs-target="#collapse{{slug($key)}}" aria-expanded="true" aria-controls="collapse{{slug($key)}}">
                                        @lang($key)
                                    </button>
                                </h5>
                                <div id="collapse{{slug($key)}}" class="accordion-collapse collapse {{ $key == 0 ? 'show' : '' }}" aria-labelledby="heading{{slug($key)}}"
                                    data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <div class="table-parent table-responsive">
                                            <table class="table table-striped">
                                                <thead>
                                                    <tr>
                                                        <th scope="col">@lang('ID')</th>
                                                        <th scope="col">@lang('Name')</th>
                                                        <th scope="col">@lang('Rate Per 1K')</th>
                                                        <th scope="col">@lang('Min')</th>
                                                        <th scope="col">@lang('Max')</th>
                                                        <th scope="col">@lang('Description')</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach($service as $key => $row)
                                                        <tr>
                                                            <td data-label="@lang('ID')">{{$row->id}}</td>
                                                            <td data-label="@lang('Name')">@lang($row->service_title)</td>
                                                            <td data-label="@lang('Rate Per 1k')">@lang(config('basic.currency_symbol')){{($row->user_rate) ?? $row->price}}</td>
                                                            <td data-label="@lang('Min')">@lang($row->min_amount)</td>
                                                            <td data-label="@lang('Max')">@lang($row->max_amount)</td>
                                                            <td data-label="@lang('Description')" class="action">
                                                                <button data-bs-toggle="modal" data-bs-target="#describeModal"
                                                                    id="details"
                                                                    data-servicetitle="{{$row->service_title}}"
                                                                    data-id="{{$row->id}}"
                                                                    data-description="{{$row->description}}">
                                                                    <i class="fal fa-eye"></i>
                                                                </button>
                                                            </td>
                                                        </tr>
                                                    @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @empty
                            <p class="text-center">@lang('No data found!')</p>
                        @endforelse
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Describe Modal -->
    <div class="modal fade" id="describeModal" tabindex="-1" aria-labelledby="describeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="title"></h5>
                    <button type="button" class="close-btn" data-bs-dismiss="modal" aria-label="Close">
                        <i class="fal fa-times"></i>
                    </button>
                </div>
                <div class="modal-body">
                    <p id="servicedescription"></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn-Msader btn2" data-bs-dismiss="modal">@lang('Close')</button>
                    <a href="" type="submit" class="btn-Msader order-now">@lang('Order Now')</a>
                </div>
            </div>
        </div>
    </div>

@endsection



@push('script')
    <script>
        "use strict";
        $(document).ready(function () {
            $(document).on('click', '#details', function () {
                var title = $(this).data('servicetitle');
                var description = $(this).data('description');

                var id = $(this).data('id');
                var orderRoute = "{{route('user.order.create')}}" + '?serviceId=' + id;
                $('.order-now').attr('href', orderRoute);

                $('#title').text(title);
                $('#servicedescription').html(description);
            });
        });
    </script>
@endpush